# Ex1 - Filtering and Sorting Data

This time we are going to pull data directly from the internet.
Special thanks to: https://github.com/justmarkham for sharing the dataset and materials.

### Step 1. Import the necessary libraries

In [3]:
import numpy as np
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv).

### Step 3. Assign it to a variable called chipo.

In [4]:
path = 'https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv'
chipo = pd.read_csv(path, sep='\t')

In [6]:
chipo.head(10)

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
5,3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",$10.98
6,3,1,Side of Chips,NaN,$1.69
7,4,1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$11.75
8,4,1,Steak Soft Tacos,"[Tomatillo Green Chili Salsa, [Pinto Beans, Ch...",$9.25
9,5,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Pinto...",$9.25

### Step 4. How many products cost more than $10.00?

In [7]:
x = '$10.98'
change = lambda x : float(x[1:])

In [11]:
chipo['item_price'] = chipo.item_price.apply(change)

In [14]:
chipo.query('item_price > 10').item_name.nunique()

31

### Step 5. What is the price of each item? 
###### print a data frame with only two columns item_name and item_price

In [20]:
chipo.groupby('item_name').item_price.mean().to_frame()

                                       item_price
item_name
6 Pack Soft Drink                        6.610185
Barbacoa Bowl                           10.187273
Barbacoa Burrito                         9.832418
Barbacoa Crispy Tacos                   10.928182
Barbacoa Salad Bowl                     10.640000
Barbacoa Soft Tacos                     10.018400
Bottled Water                            1.867654
Bowl                                    14.800000
Burrito                                  7.400000
Canned Soda                              1.320577
Canned Soft Drink                        1.457641
Carnitas Bowl                           10.833971
Carnitas Burrito                        10.132712
Carnitas Crispy Tacos                   11.137143
Carnitas Salad                           8.990000
Carnitas Salad Bowl                     11.056667
Carnitas Soft Tacos                      9.398500
Chicken Bowl                            10.113953
Chicken Burrito                         10.082857
Chicken Crispy Tacos                    10.045319
Chicken Salad                            9.010000
Chicken Salad Bowl                      11.170455
Chicken Soft Tacos                       9.635565
Chips                                    2.342844
Chips and Fresh Tomato Salsa             3.285091
Chips and Guacamole                      4.595073
Chips and Mild Fresh Tomato Salsa        3.000000
Chips and Roasted Chili Corn Salsa       3.084091
Chips and Roasted Chili-Corn Salsa       2.390000
Chips and Tomatillo Green Chili Salsa    3.087209
Chips and Tomatillo Red Chili Salsa      3.072917
Chips and Tomatillo-Green Chili Salsa    2.544194
Chips and Tomatillo-Red Chili Salsa      2.987500
Crispy Tacos                             7.400000
Izze                                     3.390000
Nantucket Nectar                         3.641111
Salad                                    7.400000
Side of Chips                            1.840594
Steak Bowl                              10.711801
Steak Burrito                           10.465842
Steak Crispy Tacos                      10.209714
Steak Salad                              8.915000
Steak Salad Bowl                        11.847931
Steak Soft Tacos                         9.746364
Veggie Bowl                             10.211647
Veggie Burrito                           9.839684
Veggie Crispy Tacos                      8.490000
Veggie Salad                             8.490000
Veggie Salad Bowl                       10.138889
Veggie Soft Tacos                       10.565714

### Step 6. Sort by the name of the item

In [23]:
chipo.groupby('item_name').item_price.mean().to_frame().sort_index()

                                       item_price
item_name
6 Pack Soft Drink                        6.610185
Barbacoa Bowl                           10.187273
Barbacoa Burrito                         9.832418
Barbacoa Crispy Tacos                   10.928182
Barbacoa Salad Bowl                     10.640000
Barbacoa Soft Tacos                     10.018400
Bottled Water                            1.867654
Bowl                                    14.800000
Burrito                                  7.400000
Canned Soda                              1.320577
Canned Soft Drink                        1.457641
Carnitas Bowl                           10.833971
Carnitas Burrito                        10.132712
Carnitas Crispy Tacos                   11.137143
Carnitas Salad                           8.990000
Carnitas Salad Bowl                     11.056667
Carnitas Soft Tacos                      9.398500
Chicken Bowl                            10.113953
Chicken Burrito                         10.082857
Chicken Crispy Tacos                    10.045319
Chicken Salad                            9.010000
Chicken Salad Bowl                      11.170455
Chicken Soft Tacos                       9.635565
Chips                                    2.342844
Chips and Fresh Tomato Salsa             3.285091
Chips and Guacamole                      4.595073
Chips and Mild Fresh Tomato Salsa        3.000000
Chips and Roasted Chili Corn Salsa       3.084091
Chips and Roasted Chili-Corn Salsa       2.390000
Chips and Tomatillo Green Chili Salsa    3.087209
Chips and Tomatillo Red Chili Salsa      3.072917
Chips and Tomatillo-Green Chili Salsa    2.544194
Chips and Tomatillo-Red Chili Salsa      2.987500
Crispy Tacos                             7.400000
Izze                                     3.390000
Nantucket Nectar                         3.641111
Salad                                    7.400000
Side of Chips                            1.840594
Steak Bowl                              10.711801
Steak Burrito                           10.465842
Steak Crispy Tacos                      10.209714
Steak Salad                              8.915000
Steak Salad Bowl                        11.847931
Steak Soft Tacos                         9.746364
Veggie Bowl                             10.211647
Veggie Burrito                           9.839684
Veggie Crispy Tacos                      8.490000
Veggie Salad                             8.490000
Veggie Salad Bowl                       10.138889
Veggie Soft Tacos                       10.565714

### Step 7. What was the quantity of the most expensive item ordered?

In [67]:
# most_exp = chipo.groupby('item_name').item_price.max().sort_values(ascending=False).head(1).index[0]
most_exp = chipo.groupby('item_name').item_price.max().nsmallest(5).index

In [68]:
most_exp

Index(['Chips and Roasted Chili-Corn Salsa',
       'Chips and Mild Fresh Tomato Salsa', 'Izze', 'Canned Soda',
       'Chips and Tomatillo-Green Chili Salsa'],
      dtype='object', name='item_name')

In [69]:
quantities = []
for item in most_exp:
    quantity = chipo.query("item_name == @item").quantity.sum()
    quantities.append(quantity)

In [70]:
quantities

[18, 1, 20, 126, 33]

In [71]:
pd.DataFrame({'item': most_exp, 'quantities': quantities})

                                    item  quantities
0     Chips and Roasted Chili-Corn Salsa          18
1      Chips and Mild Fresh Tomato Salsa           1
2                                   Izze          20
3                            Canned Soda         126
4  Chips and Tomatillo-Green Chili Salsa          33

In [40]:
chipo.query("item_name == @most_exp").quantity.sum() # hard-code

130

### Step 8. How many times was a Veggie Salad Bowl ordered?

In [77]:
chipo.query("item_name == 'Veggie Salad Bowl'").order_id.nunique()

18

### Step 9. How many times did someone order more than one Canned Soda?

In [79]:
chipo.query("item_name == 'Canned Soda' & quantity > 1").order_id.nunique()

18